from .base import AdminView
from .admin_login import AdminLogin
from .overview import Overview
from .ports import Ports
from .balance_calibration import BalanceCalibration
from .cleaning import Cleaning
from .settings import Settings
from .system import System
from .remove_recipe import RemoveRecipe
