name: Build all firmwares

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build mainboard firmware
      run: |
        cd firmware/mainboard/
        platformio run
    - name: Build balance firmware
      run: |
        cd firmware/balance/
        platformio run
    - name: Build mixer firmware
      run: |
        cd firmware/mixer/
        platformio run
    - name: Build straw firmware
      run: |
        cd firmware/straw/
        platformio run
    - name: Build crusher firmware
      run: |
        cd firmware/crusher/
        platformio run
