name: Raspberry Archive
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Raspberry Archive
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        path: 'raspberry'
        filename: 'raspberry.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build mainboard firmware
      run: |
        cd firmware/mainboard/
        platformio run
        cp .pio/build/esp32dev/firmware.bin ../mainboard.bin
    - name: Build balance firmware
      run: |
        cd firmware/balance/
        platformio run -e atmega_usbasp
        cp .pio/build/atmega_usbasp/firmware.hex ../balance.hex
    - name: Build mixer firmware
      run: |
        cd firmware/mixer/
        platformio run -e atmega_usbasp
        cp .pio/build/atmega_usbasp/firmware.hex ../mixer.hex
    - name: Build straw firmware
      run: |
        cd firmware/straw/
        platformio run -e atmega_usbasp
        cp .pio/build/atmega_usbasp/firmware.hex ../straw.hex
    - name: Build crusher firmware
      run: |
        cd firmware/crusher/
        platformio run -e atmega_usbasp
        cp .pio/build/atmega_usbasp/firmware.hex ../crusher.hex
    - name: Firmware Archive
      uses: vimtor/action-zip@v1
      with:
        files: firmware/crusher.hex firmware/balance.hex firmware/mixer.hex firmware/straw.hex firmware/mainboard.bin firmware/tool-avrdude/ firmware/flash.bat
        recursive: true
        dest: firmware.zip
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: raspberry.zip, firmware.zip
        token: ${{ secrets.GITHUB_TOKEN }}
