name: Raspberry Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Raspberry Archive
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        path: 'raspberry'
        filename: 'raspberry.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "raspberry.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
